# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Squizit
timezone: America/Denver
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Squizit creates high-quality events, media, and software to make the world
  more fun to live in. Fantasies can be real, and we will do them justice.
baseurl: "" # the subpath of your site, e.g. /blog
cover: img/cover.png # Default image shown in social media
logo: img/logo.svg

google-analytics-id: UA-104876043-1

# Social
twitter: Squizit
github:  squizit
facebook:

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
    style: compressed

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - readme.md
  - todo.md

# Other stuff
theme-color: 4CAF50 # Has nothing to do with site colors
