---
title: Squizit
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@squizit.net
description: 'We are a group of creators who want to share what me make.

'
baseurl: ''
cover: "/img/cover.png"
logo: "/img/squizit-icon.png"
google-analytics-id: UA-104876043-1
twitter: Squizit
github: squizit
facebook: 
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate
sass:
  style: compressed
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- readme.md
- todo.md
theme-color: 4CAF50
